version: '3'
services:
  deploy-app:
    container_name: deply-app
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8090:8000'
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/dist
